SCHEMA_TABLE_PROPERTIES = 'schema'
BQ_MAPPING_TABLE_COL_COLUMN_NAME = 'column_name'
BQ_MAPPING_TABLE_POLICY_TAG_COLUMN_NAME = 'policy_tag_uri'

API_REPR_POLICY_TAG_KEY = 'policyTags'
API_REPR_POLICY_TAG_VALUE = 'names'
